# Generated by Django 5.1 on 2026-08-11 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[("slack", "Slack Webhook"), ("email", "Email")],
                        max_length=20,
                    ),
                ),
                ("channel_config", models.JSONField()),
                (
                    "severity_filter",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="core.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlertHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("failed", "Failed")], max_length=10
                    ),
                ),
                ("response_body", models.TextField(blank=True, default="")),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_history",
                        to="incidents.incident",
                    ),
                ),
                (
                    "alert_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="alerts.alertrule",
                    ),
                ),
            ],
        ),
    ]
