# Generated by Django 5.1 on 2026-08-11 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("raw_response", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WorkloadCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namespace", models.CharField(max_length=255)),
                (
                    "controller_kind",
                    models.CharField(default="deployment", max_length=50),
                ),
                ("controller_name", models.CharField(max_length=255)),
                ("pod", models.CharField(blank=True, default="", max_length=255)),
                (
                    "network_cost_total",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("network_egress_bytes", models.BigIntegerField(default=0)),
                (
                    "network_cross_zone_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "network_cross_region_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "network_internet_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_costs",
                        to="collector.costsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot__timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="costsnapshot",
            index=models.Index(
                fields=["project", "-timestamp"], name="collector_c_project_389f53_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="costsnapshot",
            unique_together={("project", "window_start", "window_end")},
        ),
        migrations.AddIndex(
            model_name="workloadcost",
            index=models.Index(
                fields=["namespace", "controller_name"],
                name="collector_w_namespa_b50109_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workloadcost",
            index=models.Index(
                fields=["snapshot"], name="collector_w_snapsho_2a7ee9_idx"
            ),
        ),
    ]
