# Generated by Django 5.1 on 2026-08-11 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("detector", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="K8sEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("deployment", "Deployment"),
                            ("replicaset", "ReplicaSet"),
                            ("statefulset", "StatefulSet"),
                            ("daemonset", "DaemonSet"),
                            ("configmap", "ConfigMap"),
                            ("secret", "Secret"),
                            ("service", "Service"),
                            ("hpa", "HorizontalPodAutoscaler"),
                        ],
                        max_length=30,
                    ),
                ),
                ("namespace", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("scale", "Scale"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.JSONField(default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="k8s_events",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Correlation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_delta_seconds", models.IntegerField()),
                ("confidence_score", models.FloatField()),
                ("explanation", models.TextField()),
                (
                    "anomaly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correlations",
                        to="detector.anomaly",
                    ),
                ),
                (
                    "k8s_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correlations",
                        to="correlator.k8sevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence_score"],
            },
        ),
        migrations.AddIndex(
            model_name="k8sevent",
            index=models.Index(
                fields=["project", "-timestamp"], name="correlator__project_d7ee9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="k8sevent",
            index=models.Index(
                fields=["namespace", "name"], name="correlator__namespa_bdc122_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="correlation",
            unique_together={("anomaly", "k8s_event")},
        ),
    ]
