# Generated by Django 5.1 on 2026-08-11 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("collector", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnomalyThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric",
                    models.CharField(default="network_cost_total", max_length=50),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("pct_change", "Percentage Change"),
                            ("zscore", "Z-Score"),
                        ],
                        default="pct_change",
                        max_length=20,
                    ),
                ),
                ("warning_value", models.FloatField(default=2.0)),
                ("critical_value", models.FloatField(default=5.0)),
                ("baseline_window_hours", models.IntegerField(default=168)),
                (
                    "min_cost_threshold",
                    models.DecimalField(decimal_places=4, default=0.01, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thresholds",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("metric", models.CharField(max_length=50)),
                (
                    "baseline_value",
                    models.DecimalField(decimal_places=6, max_digits=12),
                ),
                ("spike_value", models.DecimalField(decimal_places=6, max_digits=12)),
                ("deviation_score", models.FloatField()),
                (
                    "severity",
                    models.CharField(
                        choices=[("warning", "Warning"), ("critical", "Critical")],
                        max_length=10,
                    ),
                ),
                ("namespace", models.CharField(max_length=255)),
                ("controller_name", models.CharField(max_length=255)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="core.project",
                    ),
                ),
                (
                    "workload_cost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="collector.workloadcost",
                    ),
                ),
                (
                    "threshold",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="detector.anomalythreshold",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-detected_at"],
                        name="detector_an_project_89bbe5_idx",
                    ),
                    models.Index(
                        fields=["namespace", "controller_name"],
                        name="detector_an_namespa_520f69_idx",
                    ),
                ],
            },
        ),
    ]
