# Generated by Django 5.1 on 2026-08-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="baseline_window_hours",
            field=models.IntegerField(default=168),
        ),
        migrations.AddField(
            model_name="project",
            name="min_cost_threshold",
            field=models.DecimalField(decimal_places=4, default=0.01, max_digits=10),
        ),
        migrations.AddField(
            model_name="project",
            name="retention_days",
            field=models.IntegerField(default=30),
        ),
    ]
